### PR TITLE
Support newer versions of gilded-wordpress, node-wordpress

### PR DESCRIPTION
**Pull request by staabm**
Depends on 
- [x] https://github.com/scottgonzalez/grunt-wordpress/pull/23
- [x] https://github.com/scottgonzalez/gilded-wordpress/pull/4

### CODE REVIEW

**Comment by staabm** [comment]
@scottgonzalez since the dependt PRs are merged this should be ready to go

**Comment by staabm** [comment]
Ping @scottgonzalez

**Comment by staabm** [comment]
any chanche we get a new release containing this commit?

every now and then when I need to re-setup a grunt-jquery-content based wp, I ran into this issue again :-(

**Comment by scottgonzalez** [comment]
v3.0.3 has been released.

**Pull request closed without merging**
