### PR TITLE
API sites: Make anchors for object properties and method arguments

### PR DESCRIPTION
**Pull request by gibson042**

### CODE REVIEW

**Comment by gibson042** [comment]
I just noticed that this was still open. Any plans to land it?

**Comment by mgol** [comment]
@gibson042 if no one else objects I can land it. I'm not that familiar with XSLT, though so I'll just ask: are you convinced it works properly? Have you tested it locally?

**Comment by gibson042** [comment]
Yes, I tested it with api.jquery.com. And I just remembered that it doesn't add links targeting the new property/argument ids (e.g., around the \<strong> elements that serve as headings), in order to avoid affecting any styles (e.g., adding underlines to those headings). So as a result, the new ids are visible only in Dev Tools. I figure that can change later if so desired.

**Comment by gibson042** [comment]
@mgol I just noticed the absence of these anchors again, and was just about to propose these changes again, until remembering that I already had. How about merging now?

**Comment by mgol** [comment]
Landed. Thanks for the reminder.

**Comment by mgol** [comment]
I don't have publish rights to this package on npm. @dmethvin could you publish it? I assume `npm version patch` followed by `npm publish` should be fine. Or you can add me to the maintainers list, whichever you prefer.

**Comment by jzaefferer** [comment]
Only if you have 2FA enabled 💩 :shipit:

**Comment by jzaefferer** [comment]
Done

**Comment by mgol** [comment]
Thank you!
-- 
Michał Gołębiowski-Owczarek

**Pull request merged**
