### PR TITLE
API sites: Support multiple return types in function parameters

### PR DESCRIPTION
**Pull request by anderlaw**
Cause I signed the wrong CLA data, So I update my commits and make a new PR against [this one](https://github.com/jquery/grunt-jquery-content/pull/77)

Fixes https://github.com/jquery/api.jquery.com/issues/1184

### CODE REVIEW

**Comment by mgol** [comment]
Thanks! For the sake of the future, you don't need to create a new PR in case of such issues. It's better to do changes on the same branch and push, potentially with the `--force` (or, better, `--force-with-lease`) flag and the PR will get updated automatically. This ways is better as then you have all the discussion history.

This should still be possible, I think, let me try closing this PR & re-opening the original one.

**Comment by mgol** [comment]
OK, it's not possible anymore since you removed or force-pushed the branch after closing the PR. Let's remember about that in the future, though.

**Comment by mgol** [comment]
Also, it's best to leave the `main` branch as following the upstream repository and not do any modifications to it but to instead create a separate branch for a PR. We have some guidelines on our Contribute page: https://contribute.jquery.org/commits-and-pull-requests/

**Comment by anderlaw** [comment]
😁, I gotta admit that I did not read the guidelines well, I will definitely do that next time. Thanks for the suggestions

**Review by mgol — APPROVED** [review]
I've just tested it; works great, thanks!

**Pull request merged**
