### PR TITLE
support multi return types

### PR DESCRIPTION
**Pull request by anderlaw**
this pr is about to resolve the problem [here](https://github.com/jquery/api.jquery.com/issues/1184),thanks

### CODE REVIEW

**Comment by mgol** [comment]
Please sign our CLA; you need to click on the Details link next to the `licence/cla` check.

**Comment by mgol** [comment]
Thanks for the PR! I'll review it later.

Please sign our CLA; you need to click on the Details link next to the `licence/cla` check.

**Comment by anderlaw** [comment]
I don't know why this still remains cause I have already signed it, you can see the information below:
image

**Comment by mgol** [comment]
@anderlaw The data with which you submitted the CLA needs to match the author data for all the commits in the PR. You may need to amend the commit with the details with which you signed the CLA for it to be recognized.

**Comment by mgol** [comment]
A continuation in #80.

**Pull request closed without merging**
